import Foundation.Quantum.SpectralStages

/-! Extension of actual local spectral opens to their future context domain.
Every external spectral open is generated by these extensions. This classical
external-frame result is not the constructive covering/universal-property
identification in Heunen 5.3.16. -/
namespace Foundation.Quantum.Bohr
noncomputable section
set_option backward.isDefEq.respectTransparency false
variable {A : Type} [CStarAlgebra A]

/-- Extend a local open by inverse image at every larger context. -/
def extendLocal (C : Context A) (U : TopologicalSpace.Opens C.Spectrum) : SpectralOpen A where
  carrier := {p | ∃ h : C ≤ p.1, Context.restrict h p.2 ∈ U}
  is_open' := ⟨by
    intro D
    by_cases h : C ≤ D
    · have heq : (fun x : D.Spectrum => (⟨D,x⟩ : SpectrumBundle A)) ⁻¹'
          {p | ∃ h : C ≤ p.1, Context.restrict h p.2 ∈ U} =
          (Context.restrict h) ⁻¹' (U : Set C.Spectrum) := by
        ext χ
        simp only [Set.mem_preimage, Set.mem_ofPred_eq]
        exact ⟨fun ⟨_,hx⟩ => hx, fun hx => ⟨h,hx⟩⟩
      rw [heq]
      exact U.isOpen.preimage (Context.restrict h).continuous
    · have heq : (fun x : D.Spectrum => (⟨D,x⟩ : SpectrumBundle A)) ⁻¹'
          {p | ∃ h : C ≤ p.1, Context.restrict h p.2 ∈ U} = ∅ := by
        ext χ
        exact ⟨fun ⟨h',_⟩ => (h h').elim, False.elim⟩
      rw [heq]
      exact isOpen_empty,
    by
      intro D E hDE χ hx
      obtain ⟨hCD,hx⟩ := hx
      exact ⟨hCD.trans hDE,hx⟩⟩

theorem extendLocal_le_domain (C : Context A) (U : TopologicalSpace.Opens C.Spectrum) :
    extendLocal C U ≤ contextOpen C := fun _ ⟨h,_⟩ => h

def liftLocal (C : Context A) (U : TopologicalSpace.Opens C.Spectrum) : StageFrame C :=
  ⟨extendLocal C U, extendLocal_le_domain C U⟩

/-- Lifting retains the original local spectral proposition exactly. -/
@[simp] theorem extendLocal_fiber_self (C : Context A) (U : TopologicalSpace.Opens C.Spectrum) :
    (extendLocal C U).fiber C = U := by
  ext χ
  change (∃ h : C ≤ C, Context.restrict h χ ∈ U) ↔ χ ∈ U
  constructor
  · rintro ⟨h,hx⟩
    have heq : Context.restrict h = ContinuousMap.id C.Spectrum := Context.restrict_id C
    simpa only [heq, ContinuousMap.id_apply] using hx
  · intro hx
    refine ⟨le_rfl,?_⟩
    simpa only [Context.restrict_id, ContinuousMap.id_apply] using hx

/-- The map into the stage frame is faithful on local propositions. -/
theorem liftLocal_injective (C : Context A) : Function.Injective (liftLocal C) := by
  intro U V h
  have hh := congrArg (fun W : StageFrame C => W.val.fiber C) h
  simpa only [liftLocal, extendLocal_fiber_self] using hh

theorem extendLocal_fiber {C D : Context A} (h : C ≤ D)
    (U : TopologicalSpace.Opens C.Spectrum) :
    (extendLocal C U).fiber D = Context.transportOpen h U := by
  ext χ
  change (∃ h' : C ≤ D, Context.restrict h' χ ∈ U) ↔ Context.restrict h χ ∈ U
  exact ⟨fun ⟨_,hx⟩ => hx, fun hx => ⟨h,hx⟩⟩

/-- Persistence is precisely what makes each local extension lie below U. -/
theorem extendLocal_fiber_le (U : SpectralOpen A) (C : Context A) :
    extendLocal C (U.fiber C) ≤ U := by
  intro ⟨D,χ⟩ hx
  obtain ⟨h,hx⟩ := hx
  exact U.isOpen.2 C D h χ hx

/-- All external opens are generated by local spectra and context extension. -/
theorem spectralOpen_generated (U : SpectralOpen A) :
    (⨆ C : Context A, extendLocal C (U.fiber C)) = U := by
  apply le_antisymm
  · exact iSup_le (extendLocal_fiber_le U)
  · intro ⟨C,χ⟩ hx
    apply (le_iSup (fun D : Context A => extendLocal D (U.fiber D)) C)
    refine ⟨le_rfl,?_⟩
    change χ ∈ U.fiber C at hx
    simpa only [Context.restrict_id, ContinuousMap.id_apply] using hx

/-- Lifting preserves and reflects entailment; the originating fiber prevents
 any collapse when extending an observation to future contexts. -/
theorem liftLocal_le_iff (C : Context A) (U V : TopologicalSpace.Opens C.Spectrum) :
    liftLocal C U ≤ liftLocal C V ↔ U ≤ V := by
  constructor
  · intro h χ hx
    have hh : (⟨C,χ⟩ : SpectrumBundle A) ∈ (liftLocal C U).val := by
      refine ⟨le_rfl,?_⟩
      simpa only [Context.restrict_id, ContinuousMap.id_apply] using hx
    obtain ⟨hCC,hx'⟩ := h hh
    have heq : Context.restrict hCC = ContinuousMap.id C.Spectrum := Context.restrict_id C
    simpa only [heq, ContinuousMap.id_apply] using hx'
  · intro h ⟨D,χ⟩ hx
    obtain ⟨hCD,hx⟩ := hx
    exact ⟨hCD,h hx⟩

end
end Foundation.Quantum.Bohr
